logConfig:
  level: "debug"
  filePath: "logs/calendar_sender.log"

dbConfig:
  host: "localhost"
  port: 5432
  dbName: "db_calendar"
  user: "db_calendar_user"
  pass: "db_calendar_pass"
  itemsPerQuery: 50
  repoType: "psql"

queueConfig:
  user: "guest"
  pass: "guest"
  host: "localhost"
  port: 5672
  queueName: "events"
  exchangeType: "direct"
  scanTimeout: 10