host="localhost"
port="8082"
logConfig_level="debug"
logConfig_filePath="logs/calendar.log"
repoType="psql"
dbConfig_host="localhost"
dbConfig_port="5432"
dbConfig_dbName="db_calendar"
dbConfig_user="db_calendar_user"
dbConfig_pass="db_calendar_pass"
dbConfig_itemsPerQuery="50"
dbConfig_repoType="psql"
grpcAddress="localhost:50051"
httpAddress="localhost:50052"
goose -dir ./migrations postgres "host=127.0.0.1 user=$dbConfig_user password=$dbConfig_pass  dbname=$dbConfig_dbName sslmode=disable" up
